### ISSUE TITLE
Add Zippyshare

### ISSUE THREAD

**Issue by enilsen16** [berrberr/streamkeys#150]
Zippyshare.com

**Comment by enilsen16** [comment]
Here's an example of music and their crappy flash player -http://www91.zippyshare.com/v/MRwmvHKu/file.html

**Comment by berrberr** [comment]
Took a look, couldn't find any way to make it work. Basically we are looking for some global JS object that can be used to interact with the player (since we can't actually click Flash stuff) and I couldn't find it. Feel free to poke around yourself, but I get the feeling with how primitive that player is it's a no go :expressionless:
