### ISSUE TITLE
Priority list

### ISSUE THREAD

**Issue by guertijp** [berrberr/streamkeys#162]
One feature I've been looking for in any extension of this kind is the ability to only affect *one* of any open apps using a priority list.

I have Google Music on as a pinned tab pretty much permanently, but also regularly watch Netflix or YouTube and would like to be able to use media keys for both. With the current setup, unless I'm missing something, pushing Play/Pause toggles both Google Music and YouTube/Netflix at once.

With a priority list, only the highest priority app open would be triggered, so when I have YouTube up, Google Music wouldn't respond.

I think that this behavior would be much more logical than activating all enabled apps.

**Comment by berrberr** [comment]
This is a really good idea :). I am working on some changes now to add a default/favourite site and can add in something like a priority list as well. I guess one question is, what happens when you have two tabs open on the same priority level? Is there some better functionality than sending the command to both?
