### ISSUE TITLE
Fix pandora

### ISSUE THREAD

**Issue by berrberr** [berrberr/streamkeys#180]
Pandora player changed and is bugged.

**Comment by zeh-workco** [comment]
The problem seems to be this: we can't pause/play while the tab is not focused in Chrome. It does work, but veeeeeery slowly.

I think the cause is that Pandora fades audio on/off while playing and pausing. But they probably do so with `setTimeout` calls, which on Chrome is throttled to a minimum of 1000ms while running on a non-focused tab.

Pandora's code seem to check for a `enableAudioFade` option before enabling this feature. I couldn't find a place to change this though. Injecting `false` to this check might fix the behavior.

**Comment by berrberr** [comment]
@zeh-workco Thanks for looking at it :)

Seems like Pandora has fixed its self -- I can't reproduce the bug anymore. Going to close for now and keep an eye out for it.

**Comment by zeh-workco** [comment]
@berrberr You're right - working as intended here. The fade has been removed altogether. So no changes necessary.

(And thanks for the great work with Streamkeys!)
