### ISSUE TITLE
Mute doesn't work?

### ISSUE THREAD

**Issue by minowaeli** [berrberr/streamkeys#184]
http://i.imgur.com/acQZ0MI.png
Mute doesn't seem to work at all no matter what shortcut I have it set to. Even the default shortcut, Ctrl + Shift + 2, doesn't work. I restarted Chrome to see if that would work, no fix. Thanks.

**Comment by berrberr** [comment]
What site is it for? Many of the sites don't actually have mute support built in to them.

**Comment by minowaeli** [comment]
I checked with Youtube and Spotify on chrome.

**Comment by berrberr** [comment]
Yeah, youtube & spotify don't actually have mute support. I guess I would suggest just pausing the site instead. Mute support is fairly sparse, mainly due to usually being the most time consuming to add & also not having much utility over just using pause (so much so that I have considered removing it entirely, but have kept it in for legacy reasons).

If you have a specific use case for mute that can't be solved by just pausing I would love to hear it though! I could totally be overlooking something :)
