### ISSUE TITLE
Add a "disable all players on Chrome start-up" or shortcut to do so ?

### ISSUE THREAD

**Issue by Mitiss** [berrberr/streamkeys#206]
Hi, I think it could be great if you can add a "disable all players on Chrome start-up" option, or a shortcut to disable all Players.
I always keep my youtube, play music and soundcloud alive when I leave Chrome. So when computer start, and I launch Chrome, I have to disable all players one by one on start-up.

**Comment by berrberr** [comment]
By disable you mean disabling the individual tab (by clicking the button in the popup) and not the whole site right?

**Comment by metaflow** [comment]
@Mitiss you can do that by assigning keyboard shortcut "stop" and pressing it right after the browser has started. There is no UI button for that.
As for "browser startup" - I believe it's very tricky to detect that from extension standpoint.

**Comment by nemchik** [comment]
The reason i tagged #372 is because I am guessing the reason behind  your request is that you want all players disabled by default so that when you use media keys only one at a time will actually respond depending on which one you activated manually. I think #372 would actually provide functionality that would negate the need to disable all, because only your most recently playing tab would respond to media keys.

If that sounds right, please let us know because #372 is looking pretty good to merge and it could close your issue if you agree this meets your need.

**Comment by Mitiss** [comment]
Thank you, I even didn't hope replies after such time.
Unfortunately #372 doen't match what I want. It could match if the "stop all players" shorcut was really stopping all players EVEN THOSE that are disabled or that are having inferior priority.
I need a shortcut that stop all players, even those having inferior priority, because I use Youtube (priority 3), PlayMusic (priority 4) or Soundcloud (priority 5).

**Comment by nemchik** [comment]
@Mitiss that sounds like strange behavior. If I have YouTube and SoundCloud both open and both playing and neither is disabled and I press the STOP media key, the both stop. If #372 were to merge this would still be true because it ensures a STOP media key is sent to all players.

Could you try with the current plugin to leave all players enabled and press the STOP media key?

**Comment by Mitiss** [comment]
If all players have the same priority it work as you mentioned.
But I use different level of priority : Youtube (priority 3), PlayMusic (priority 4) or Soundcloud (priority 5). In my case, when I press stop shortcut it only stop the higher prioritized player (it stop SoundCloud).

**Comment by nemchik** [comment]
Oh, I see now, I forgot about priorities. Is there a reason you're using priorities? I have everything set to 1.

**Comment by Mitiss** [comment]
I have a lot of tabs opened in Chrome : I have several YouTube tabs, several SoundCloud tabs, one Google Play Music.
And sometime YouTube video are starting by themselves...  so if a button could stop all players it will be useful.

But thanks to priority setting the stop button is not as needed as before. So if the development of this feature is not programmed exist it doesn't matter.

**Comment by nemchik** [comment]
@Mitiss are you familiar with running the extension from source? If so I would be curious if you would try cherry picking #372 and setting all of your players to the same priority and then trying the STOP media key, and also trying the other media keys.

If you're not familiar with running from source I'd be happy to try and walk you through it, but be warned it's not for the faint of heart :)
