### ISSUE TITLE
Toggle Option

### ISSUE THREAD

**Issue by leocaseiro** [berrberr/streamkeys#217]
Hi, I've just started using it for Youtube and some other players.

I was wondering if we could have an easy toggle option to enable the `streamkeys` or disable quickly.

So I don't need to enable or disable on chrome extensions which are, honestly, quite annoying.

I've seen your FAQ, and I do understand that.

> FAQ: Why do my iTunes/Windows Media Player/etc media keys not work after I install this extension?

I haven't read your source code yet, but I believe we could have a boolean option to load or don't load the JS/etc...

I'm happy to try to implement myself and send you a PR, but I would like to know your thoughts before handling it.

Thanks

**Comment by leocaseiro** [comment]
Currently, I'm using the [Extensions Manager (aka Switcher)](https://chrome.google.com/webstore/detail/extensions-manager-aka-sw/lpleipinonnoibneeejgjnoeekmbopbc) which is quite useful.

**Comment by berrberr** [comment]
So, an extension can _disable_ itsself, but once it does there is no way for an extension to enable itsself from a disabled state (because it's disabled! :D)

The switcher extension works by using [`chrome.management.setEnabled`](https://developer.chrome.com/extensions/management#method-setEnabled) on _other_ extensions not itsself. That's how it can enable disabled extensions.

So, we could add a hotkey/toggle in the popup to disable streamkeys really easy, but enabling it back is not possible (unless I am missing something). And I don't really know how useful a disable switch would be to people.

**Comment by Brozgar** [comment]
Hmm, what if we just stop execution of everything that belongs to the plugin instead of completely disabling it? Something similar to Adblock's pause function, I guess...

**Comment by leocaseiro** [comment]
That was my ideia though

**Comment by wetfirer** [comment]
**
_Hmm, what if we just stop execution of everything that belongs to the plugin instead of completely disabling it?_
**
IMO that wouldn't stop Chrome hijacking the multimedia keys for SK, would it? The point of that feature is that one can switch between youtube and winamp (as an example) without any hustle .

It is really weird situation, because I need those keys as global since Chrome plays youtube in background and minimized while I am working. So even if it would allow to them keys being used for Chrome, it would be of no good to many of us. 

I am thinking of a custom additional extension (yep, like switcher), which could stay on as a listener and to which could be assigned specific custom key combination (which would always stay global and resident, while Chrome is ON). If that is not that hard I am quite OK to have an additional extension ONLY for that.

What do you people think of that? 

Later on there's a lot of space for further development of that add-on, since it would be quite needed. The current switcher is developed no more, an alternative is at its baby age and both had no shortcut functionality. 

What do you think? :-)
