### ISSUE TITLE
[Feature Request] Free global hotkey

### ISSUE THREAD

**Issue by RafaelKr** [berrberr/streamkeys#226]
Could you please add the possibility to quickly disable the plugin, so that the global hotkey is free for another application like Spotify or another media player? Or isn't that possible, if the handler once is set?

**Comment by TheKnarf** [comment]
I would also like that feature. I started to wonder why my media keys stopped working in Spotify on my Mac and the reason was that Streamkeys was "highjacking" them. Would be great to see a solution too this other having to manually enable/disable the Streamkeys-extension.

**Comment by berrberr** [comment]
It's possible to add a hotkey to disable the extension, however it's impossible to have a hotkey to enable it again (since the extension is disabled :D). See: https://github.com/berrberr/streamkeys/issues/183

I know some people have used "Chrome Extensions Manager" (https://chrome.google.com/webstore/detail/extensions-manager-aka-sw/lpleipinonnoibneeejgjnoeekmbopbc?hl=en) to quickly disable/enable Streamkeys & free the hotkeys. You can also bind the Streamkeys hotkeys to something other than media keys (which is what I do)

**Comment by garmoshka-mo** [comment]
Same annoying issue

@berrberr Is there possibility to unbind hotkeys once last **enabled music site** closed? 
By event or by setInterval(,1000). And bind again, once tab with any **enabled music site** opened

That would create natural user experience, like when I have iTunes and Spotify both open - 
"Play" button will launch either of them, and if I it's not what I expected - I will simply close that application

**Comment by berrberr** [comment]
@garmoshka-mo I agree, that would be great. Unfortunately changing hotkeys is not possible with the current API. As you can see, the `chrome.commands` api is very barebones: https://developer.chrome.com/extensions/commands
