### ISSUE TITLE
The keys no longer work on other programs if a chrome window is open.

### ISSUE THREAD

**Issue by BenasMot** [berrberr/streamkeys#329]
Unless a full-screen program is on.
Bug occurs when using the spotify app, but chrome is in the background (with for example Gmail open).
If a full-screen app (a game) is open on top, then buttons prioritize spotify first. 

Sorry for messy English. I'm really tired right now.

**Comment by nemchik** [comment]
If I am understanding what you are describing correctly I believe this is a bug with Chrome, not Streamkeys.

If Chrome is open, even if you have no tabs open with media in them, global hotkeys will not work in other programs such as the Spotify desktop app, or Windows Media Player.

The bug is mentioned here:
https://bugs.chromium.org/p/chromium/issues/detail?id=396991 and
http://www.omgchrome.com/chrome-google-music-media-keys/ and
https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Media-keys-no-longer-work/td-p/807591

Again this is not something that one specific extension (like Streamkeys, or any other) has any control over. This is how Google is handling Global Hotkeys in Chrome.

**Comment by BenasMot** [comment]
Yeah, it could be. I didn't check it without the plugin.
