### ISSUE TITLE
Let play/pause only toggle last playing tab

### ISSUE THREAD

**Issue by ottidmes** [berrberr/streamkeys#337]
I really like StreamKeys, but I would like to know whether it is possible to let play/pause only toggle the last playing tab?

I generally have multiple music playing tabs open, but obviously have only one of them playing at a time. Currently if I press my play/pause media key it will pause the currently playing tab and continue playing the previously playing tab (e.g. another youtube video). While I expect it to pause the currently playing tab, and continue playing once a press the play/pause button again. So instead of toggling between playing tabs, I expect it to toggle between playing and pausing the last playing tab.

I have looked at the settings but am unable to find anything related to this. Am I missing something? It seems like a common use case.

**Comment by metaflow** [comment]
I have exactly the same issue. @berrberr do you mind if I try to create PR? I think about adding new checkbox option and storing last stopped/paused site. If "last" is no longer present when 'play' is triggered then first one from the list (aka random) will play.

**Comment by Wizek** [comment]
@metaflow I like your suggestion and initiative of creating a pr. I might want to contribute to it too.
Also, we could maybe have a later version too that stores an array of most recently played tabs, so that in the event of closing one the second most recently played will receive take focus.

Also, I think this issue is related: https://github.com/berrberr/streamkeys/issues/322

**Comment by MondayHopscotch** [comment]
It looks like this issue can be closed since #372 has been merged now
