### ISSUE TITLE
Suggestion: A hotkey for rewinding and fast forwarding videos

### ISSUE THREAD

**Issue by gucciburg** [berrberr/streamkeys#343]
A hotkey that would allow the user to rewind/ fast forward in 5-10 second increments would be very useful.

**Comment by christophercheng** [comment]
second that

**Comment by schneivo77** [comment]
yes, like the 5 second steps in youtube when you press left or right arrow key during the video

**Comment by FantomX1-github** [comment]
agree I had to use autohotkey once again for that

**Comment by schneivo77** [comment]
Thank you so much @cubimon! This is working great! :)
For now I only tried it with youtube but there it does exactly what I wanted.

So it would be great if this could be made available for everyone by adding it to the main project by @berrberr . :)

@cubimon:
I had to change the version of **grunt-sass** to the current version (**3.0.2**) in the *package.json* because with the given version *2.1.0* there came an error when I called `npm install`.

Then I had to adjust the **Gruntfile.js** a little bit, so it worked with the newer *grunt-sass*.

I added *dart-sass* as a variable by changing ***line 9*** from this:
```javascript
files = grunt.file.expand({cwd:"code/js/"}, ["**/*.js"]);
```
to this:
```javascript
files = grunt.file.expand({cwd:"code/js/"}, ["**/*.js"]),
sass = require('dart-sass');
```

Then I told sass to use *dart-sass* by changing **line 92** from this:
```javascript
sass: {
      options: {
        sourceMap: true
      }
[...]
```
to this:
```javascript
sass: {
      options: {
        sourceMap: true,
        implementation: sass
      }
[...]
```
Before compiling I had to add the *dart-sass* package to the *package.json* by calling `npm install dart-sass`.
Then I could build the plugin either by calling `npm run develop` for debugging or `npm run grunt:rel` for production.

**Comment by cubimon** [comment]
Thank you for yor feedback, I am going to apply your change in the next few days. I would like to add the seek/volume features to a few more websites before I send a pull request, especially since @berrberr Seems to be inactive. Currently I am struggling with soundcloud, because their audio Element ist a blob for a part of a song, so there must be a different way to seek.

**Comment by noah019** [comment]
udemy.com pls 👍
