### ISSUE TITLE
[Feature] Volume up/down

### ISSUE THREAD

**Issue by MJCD** [berrberr/streamkeys#371]
Hi it'd be great if it had support where possible (netflix is my main use case) for volume up and down not just mute.

Is there any particular reason this can't be done? Otherwise would be an excellent addition.

Cheers for your hard work so far!

**Comment by nemchik** [comment]
Adding the base functionality should be pretty easy, but volume control would need to be individually added to each controller for each site (the ones that can anyway). It wouldn't be too much trouble to accomplish this for Netflix and maybe a few other popular players just to get started.

But before any of that, what buttons are you wanting to use for this? Is there a reason you don't just use the system volume control that adjusts the volume on your whole system? Or are you wanting to map special buttons to control the volume of the players with streamkeys while leaving your system volume alone?

**Comment by MJCD** [comment]
Personally I want to use this with my chromecast and want to be able to easily change the streams volume. That could perhaps be a 'controller' of its own just for chrome's casting perhaps? 

My thinking is that Chrome would probably protect their cast stuff in some way as to make it difficult to achieve so their tech remains proprietary. I base this on the fact they disabled miracast on the chromecast series in favour of ONLY their api.

I lost my TV's remote lol-  but such devices seem rather redundant anyway when there's great software like this around.

**Comment by BenjD90** [comment]
I have the exact same problem with Deezer and my Chromecast.

**Comment by MJCD** [comment]
Volume is a system (OS) level concern not a software issue, such an action
has little utility in this extension for my 2 cents

- Michael

**Comment by cubimon** [comment]
This may be the case for you, but not everyone. I often watch netflix/youtube and talk on discord the same time, if someone says something important I usually drop the volume of my browser/stream so I can hear discord better. But surely most people are probably pleased with system volume control or binding volume control of chromium to some keys.

**Comment by MJCD** [comment]
Windows has support for this natively, no other OS I know of has that
feature and once again requires OS level treatment/support...

- Michael

**Comment by cubimon** [comment]
@MJCD What feature has windows natively that others don't? On Linux pulseaudio/pavucontrol can be used to change volume per application/video/audio player. MPRIS  is like OSD. I did bind mpris actions on my keyboard using `bindsym` of i3wm, idk for other window mangers.

**Comment by MJCD** [comment]
It's called audio ducking afaik as well as the OS level concept of "this is
a call" "this game is not a call" etc

- Michael

**Comment by cubimon** [comment]
I know cars have stuff like this, the radio volume decreases if the navigation talks. I always felt this is pretty meh, the idea behind this is great, the user should be able to listen to stuff that is more important. But at the same time the navigation is sometimes super annoying. Maybe this is like automatic windshield wipers, at least for my car (Golf 7) they react super slow and the fact that it has "different automatic speeds" makes the automatic mode design super stupid. Idk I feel like manual modes are somtimes superior, but surely it is nice that stuff like this works automatically.

**Comment by JJ-Author** [comment]
I would be still interested in such a feature, My use cases are

- I use SpotifyWeb to play music on a SpotifyConnect Device. The SpotifyWeb volume slider is the only way to control and change the volume of that device (changing system or chrome volume has no effect since SpotifyWeb is not streaming any sound it is just dealing as a "remote controller") 
- I often listen to calm music in the background played in one chrome tab (mostly youtube, deezer, spotify), but in another chrome tab i watch a tutorial or join a conference call, participate in zoom workout where one should play its own music, etc. It occurs very often that the background music loudness changes from song to song (esp. on youtube) so that I need to adjust the volume or another person in the mentioned conference call starts to speak so silently that I quickly need to decrease the volume of the music a bit. 

any system or chrome features seem to not help here, and config options of streamkeys with priority settings and sending the commands to the most recent player would give a flexible and reliable way to "route" the volume change request instantly to the correct tab without disrupting the foreground task.
