### ISSUE TITLE
Global hotkeys no longer work

### ISSUE THREAD

**Issue by SuhasAnjaria** [berrberr/streamkeys#418]
Everytime I change stream-Keys hotkeys in the chrome::/extensions/shortcuts and try changing the scope to global, it reverts back to chrome once i exit the page.

**Comment by deecewan** [comment]
I've got this, but backwards. They're currently set to 'Global', but if I ever change them to 'In Chrome', and hit refresh, it changes back to 'Global'.

**Comment by GridTrekkor** [comment]
I installed an unpacked copy of 1.7.2 and changed the update URL in manifest.json to something that won't allow an auto-update.  This fixed the issue.

**Comment by mherrmann3** [comment]
Did you check out #409? :: reinstalling the extensions fixed it (for others and for me)

**Comment by Makesh-Gmak** [comment]
Tired re-installing still unable to set "Toggle Play/pause" to "Global". Always sets back to "Chrome", others functions, I can able to set to "Global".

**Comment by Makesh-Gmak** [comment]
Nailed it ...
I have been using Ctrl+Shift+Pageup/down/Home/End since ages.

Source : https://developer.chrome.com/apps/commands

> The user is free to designate any shortcut as global using the UI in chrome://extensions \ Keyboard Shortcuts, but the **extension developer is limited to specifying only Ctrl+Shift+[0..9] as global shortcuts**. This is to minimize the risk of overriding shortcuts in other applications since if, for example, Alt+P were to be allowed as global, the printing shortcut might not work in other applications.

One more thing : Ctrl+Shift+[0..9] also not working as Global if you directly set through "chrome://extensions/shortcuts" . I downloaded Streamkeys-1.7.3 and restricted number of keys in manifest.json to '4' as per dev guide and set the shortcuts directly in manifest and loaded those through developer mode.


`
"commands": {
    "playPause": {
      "suggested_key": {
        "default": "Ctrl+Shift+2"
      },
      "global": true,
      "description": "Toggle play/pause"
    },
    "playNext": {
      "suggested_key": {
        "default": "Ctrl+Shift+3"
      },
      "global": true,
      "description": "Play next track"
    },
    "playPrev": {
      "suggested_key": {
        "default": "Ctrl+Shift+1"
      },
      "global": true,
      "description": "Play previous track"
    },
    "stop": {
      "suggested_key": {
        "default": "Ctrl+Shift+4"
      },
      "global": true,
      "description": "Stop all players"
    }
  },
`

PS: Not sure all these changes are needed, first time exploring "Chrome extension dev mode"

**Comment by SuhasAnjaria** [comment]
Please mark closed. The latest update has fixed this.
