### ISSUE TITLE
Feature Request: forward/backward keys

### ISSUE THREAD

**Issue by ToxicTryhard** [berrberr/streamkeys#453]
Keys that allow you to skip forward/backward in a song by 5/10/somethinglikethat secs

**Comment by Cubimon** [comment]
I know this is a bit older, but I am currently working on something like that/a seek feature. Try my [fork](https://github.com/Cubimon/streamkeys). It currently only works for youtube/music/twitch/netflix. If you wish another platform please tell. I am going to send a pull request to berrberr sooner or later, depending on how much more I am going to add

**Comment by nazikus** [comment]
soundcloud too, please

**Comment by cubimon** [comment]
I experimented a bit with deezer/spotify/soundcloud and the most general solution was to override the `document.createElement` function and access all audio/video elements. This list of audio/video elements can be used to seek/control volume. But soundcloud works a bit different, the audio element contains only a small portion of a whole song. They must have a more general method to seek, which creates new audio elements and which is probably uglified and hard to find. That's my current state for soundcloud

**Comment by jaekyeom** [comment]
@cubimon 
Is making changes for a subset of the services against the policy? I want to see this feature in the official StreamKeys.

**Comment by cubimon** [comment]
@jaekyeom what policy are you talking about? Currently the like/dislike/next media/previous media buttons work for a subset of all services. E.g. twitch has no next media or like/dislike functionality. Btw I solved soundcloud mostly by modifying the js source code via regex (regular patches don't really work for minified js)

**Comment by jaekyeom** [comment]
@cubimon I'll cut to the chase. Can you make a PR with those changes, so that StreamKeys on Chrome Web Store can have this feature?

**Comment by jaekyeom** [comment]
@cubimon Oh, good to know! Can't wait to see it gets merged.

**Comment by cubimon** [comment]
@nazikus soundcloud should work with my current [fork on master](https://github.com/cubimon/streamkeys)

**Comment by karlhorky** [comment]
Oh, it seems that @cubimon's fork at https://github.com/Cubimon/streamkeys is now archived:

![Screenshot 2023-09-23 at 16 41 38](https://github.com/berrberr/streamkeys/assets/1935696/81241534-04c5-4793-8cc8-434928d02edc)

@berrberr since this issue and the PR ( https://github.com/berrberr/streamkeys/pull/476 ) were just closed by the stale bot, would you consider reopening them?

Seems like a feature to jump ahead / behind 5 or 10 seconds would be a great addition to the extension.

Reopening this issue (instead of opening a new one) would allow for maintaining the context and input above.

If a new issue / PR is desired, then maybe we can make a new one instead.

Keywords for search: jump, skip, seek, forwards, backwards, scrub, scrubber

**Comment by cubimon** [comment]
Yeah I have not touched it in a while, at some point I also decided to implement it from scratch here: https://github.com/cubimon/schmidts-katz. Also chrome at some point decided to implement media keys for audio/video which should do pretty much what this plugin does (except jumping a few seconds behind/ahead), which should make this plugin deprecated, unless the chrome implementation doesn't fully work and this provides something in addition.
