### ISSUE TITLE
Youtube - stops working after a while (Ubuntu 18.04 LTS)

### ISSUE THREAD

**Issue by dseptem** [berrberr/streamkeys#475]
Media keys work perfectly, but after a while (didn't time it) they stop working.
Only solution found is to close and open Chrome, but it keeps happening.

OS: Ubuntu 18.04 LTS
Chrome: 70.0.3538.110 (Official Build) (64-bit)

**Comment by cubimon** [comment]
Can you provide some more information? what url did you play? do you use other plugins/ad blocker? how long does it take usually, seconds, minutes or hours? can you paste some error message/stack trace?

**Comment by dseptem** [comment]
URL doesn't seem to matter, I tried playing all these different albums:
https://youtu.be/LYOtZvwNCsc
https://youtu.be/pSwUztIvlBc
https://youtu.be/kDGEkRGFSjQ

I use adblock, yes, didn't try to disable it.

I'd say it takes some minutes to stop working, 30 at best IIRC.

I get no error messages, is there any way to track the problem?
What happens is that I hit my media key but chrome/streamkeys doesn't recognize it and the music doesn't stop, even if streamkeys does know that I'm playing music on youtube.

**Comment by dseptem** [comment]
I'll try tomorrow, this happens on my work notebook so I won't be able try things today.

**Comment by cubimon** [comment]
I tried [this](https://www.youtube.com/watch?v=LYOtZvwNCsc&feature=youtu.be) for ~45 minutes without issues and without any other activity (I was mostly afk). I had uBlock origin enabled. I use my fork and chrome 68.0.3440.84 (Official Build) (64-bit) on arch linux. My guess is that some new tabs in chrome reorder priority or some internal data structures, so that the message/command does not arrive on the correct controller/is stuck somewhere. Do you have the same issue on other devices? I am going to try this now on windows 10/with berrberr's streamkeys version.

**Comment by dseptem** [comment]
Tried this on my Windows desktop, no problem at all.

I think my issue might be related to this: https://github.com/berrberr/streamkeys/issues/268

I'll try disabling ubuntu media keys tomorrow.

**Comment by dseptem** [comment]
Started using another hotkey instead of the media key, no problems at all.
Didn't even bother with disabling ubuntu media keys.

**Comment by cubimon** [comment]
maybe it should be mentioned in README.md
