### ISSUE TITLE
Could it be possible to integrate with the Windows 10 media OSD?

### ISSUE THREAD

**Issue by Wizek** [berrberr/streamkeys#497]
I mean this overlay: ![ximg_55c124155c2f2 png pagespeed gp+jp+jw+pj+js+rj+rp+rw+ri+cp+md ic Z0H4w6XT11](https://user-images.githubusercontent.com/491672/54203597-d5111c00-44d2-11e9-8fde-3667d6b8ba0d.png)

Sometimes I want to switch back and forth between play-pausing a YouTube video and playing some music on Spotify. That Windows overlay can make it very easy to do so with a little arrow on the right edge that shows when there are multiple media sources available. That arrow is not on that picture (it would be at the very right edge) but I can upload another picture to show if anyone is uncertain.

I am also unsure if a Chrome extension can do such an integration in any way, but even if it can't, I think we could have a very small 100 kilobyte companion native app that could liaison between Streamkeys and Windows to make this possible. That companion native executable would be completely optional of course, and only needed to be added by those who want the extra overlay OS integration.

**Comment by cubimon** [comment]
I guess this is could be done similar to mpris. [This](https://docs.microsoft.com/en-us/windows/desktop/CoreAudio/osd) is probably an example for an osd application?

**Comment by lukas-lang** [comment]
Another benefit of this would be that issues with multiple players listening for media keys could be prevented:
Currently, StreamKeys does not work if another app is open that uses the Media OSD (since that one appears to capture any global hotkeys). Handling media keys through the OSD would allow the user to select the "active" media playback app in the OSD. The hotkeys are then forwarded to the correct app. Potentially, one could even provide an OSD "page" for each website with media playback. The user could then conveniently control all websites using the OSD.
