### ISSUE TITLE
Constantly logging "STREAMKEYS-INFO: Player state change" (even if it doesn't)

### ISSUE THREAD

**Issue by MartinLichtblau** [berrberr/streamkeys#539]
It constantly prints on console in Chrome "STREAMKEYS-INFO: Player state change" when using spotify. Of course I don't click anything nor can see that the player state changed.
The logging is not a problem in itself, but an indicator that something unexpected is going on and doing unnecessary computations in the background.

**Comment by alextsits** [comment]
Well, the player state actually changes, since the current time of the track changes. I guess this is why you see that logs. And you probably don't see them in all sites, am I right? For instance, for sites that do not support getting the current time.

**Comment by berrberr** [comment]
Yep it logs on every state change, and for sites that support time tracking this will happen every second.

It probably would be a good idea to stop doing this now actually. When the logs were initially added Streamkeys didn't support current time tracking so the log only happened on play/pause state change which doesn't happen that much. It might be cool to add something to the build step to export something so that we only log stuff for dev builds.

**Comment by nemchik** [comment]
Maybe a setting in the extension options to enable/disable the logging?

**Comment by berrberr** [comment]
@nemchik yeah that is a better idea :). Just a custom setting that defaults to false
