### ISSUE TITLE
Google Music with Extension prevents play/pause with media keys

### ISSUE THREAD

**Issue by JacobSnyder** [berrberr/streamkeys#78]
I have the [Google Play Music Extension](https://chrome.google.com/webstore/detail/google-play-music/fahmaaghhglfmonjliepjlchgpgfmobi) installed.  

The issue that I'm having is that I can't play or pause using my media keys in Google Music with the extension enabled.  I can play or pause using the Streamkeys toolbar in Chrome just fine.  But if I use the media keys on my keyboard, the music quickly pauses and then unpauses (or vice-versa).

What's interesting is that if I queue up some music to play in a Google Music tab, pause the music, close the tab, and then hit play with my media keys, the music starts playing.  What I believe is happening is that the play/pause command is sent to both the Google Music tab and the extension, causing the issue.

Disabling the extension works around the issue.  However, this isn't ideal because the extension allows me to easily add music to my library, which makes disabling/removing the extension not a great long-term fix.

**Comment by berrberr** [comment]
This is because both extensions are set to use the media keys as hotkeys, so each media key press will send the hotkey to both extensions. 

There is an easy fix for you though! Goto the Chrome extensions page (chrome://extensions) and goto the Keyboard Shortcuts link at the bottom. In that popup you can remove the Google Play Music hotkeys by clicking the little X.

The end result should be both extensions still active, but the media keys won't be sent to the Google Play extension.

**Comment by JacobSnyder** [comment]
That was really easy.  Thanks!

To prevent other users like me having the same issue, is it possible for StreamKeys to detect if the Google Play Music Extension is installed (and better yet, if it is bound to the media keys) and disable its bindings to Google Music?  Or can StreamKeys detect the pause/unpause issue and suggest a work around?

**Comment by berrberr** [comment]
I am pretty sure that that level of sophistication isn't possible, but I'll take a look. At the very least I am going to put a note up somewhere on the site about this scenario since a bunch of others have run into this problem as well :smile:
