### ISSUE TITLE
Extension prevents using Play/Pause and seek keys for Windows Media Player

### ISSUE THREAD

**Issue by PeterGIN** [berrberr/streamkeys#80]
See title; I have verified the extension is the issue by disabling it and discovering that my media keys work for Windows Media Player again.

Changing the key scope from "Global" to "In chrome" also fixed the issue, but then chrome has to be in focus in order to use the extension to control web media players. 

Is there any way to get both to work?

EDIT:
As a quick fix, you could change the "Activate extension" shortcut to a "toggle extension" shortcut. That way keys can be set to global, and you can toggle the entire extension when you want to use Windows Media Player.

**Comment by Guria** [comment]
It can't be solved by extension author. It is browser behavior.

**Comment by PeterGrega** [comment]
I see that the "Activate Extension" has nothing to do with Streamkeys, and is instead something used by Google Chrome. 

Surely instead of capturing the state of the buttons, you could just read it and repeat it? Wouldn't that allow both applications to make use of the buttons?

**Comment by Atema** [comment]
I don't think it's possible for an extension to do this kind of behaviour.

**Comment by berrberr** [comment]
As @Guria mentioned this is a Chrome issue. Because of the way that they are implemented in Chrome global hotkeys take priority over everything.

It's possible to add a shortcut to disable the extension, but then the extension will be disabled...so the shortcut to turn it back on will not work and the user will have to manually enable it via the chrome://extension tab. 

There are a couple of issues open on the chrome google code page about this behavior, so there is a chance that this will be fixed in the future...but for now there is nothing that extensions can do :(
